--- Cargo.toml.orig	2022-03-15 04:22:37 UTC
+++ Cargo.toml
@@ -14,7 +14,7 @@ readme = "README.md"
 
 [lib]
 name = "clvm_rs"
-crate-type = ["rlib"]
+crate-type = ["rlib", "cdylib"]
 
 [profile.release]
 lto = true
