--- Cargo.toml.orig	2022-10-10 16:58:47 UTC
+++ Cargo.toml
@@ -11,7 +11,7 @@ readme = "README.md"
 
 [lib]
 name = "clvmr"
-crate-type = ["rlib"]
+crate-type = ["rlib", "cdylib"]
 
 [profile.release]
 lto = true
