--- Cargo.toml.orig	2021-11-09 23:49:33 UTC
+++ Cargo.toml
@@ -29,11 +29,10 @@ bls12_381 = "=0.5.0"
 sha2 = "=0.9.5"
 
 [target.'cfg(unix)'.dependencies]
-openssl = { version = "0.10.35", features = ["vendored"] }
+openssl = { version = "0.10.35" }
 
 [target.'cfg(target_family="wasm")'.dependencies]
 wasm-bindgen = "=0.2.75"
-wasm-bindgen-test = "=0.3.25"
 
 [target.'cfg(not(target_family="wasm"))'.dependencies]
 pyo3 = "=0.14.2"
