--- Cargo.toml.orig	2022-06-21 23:28:24 UTC
+++ Cargo.toml
@@ -13,8 +13,8 @@ repository = "https://github.com/Chia-Network/clvm_rs/
 readme = "README.md"
 
 [lib]
-name = "clvmr"
-crate-type = ["rlib"]
+name = "clvm_rs"
+crate-type = ["rlib", "cdylib"]
 
 [profile.release]
 lto = true
